language: node_js

node_js:
  - "0.12"

addons:
  sauce_connect: 
    username: "CoderDojoDev"
    access_key: "d079bf09-33be-4565-aea4-f07ffd191a7d"
    no_ssl_bump_domains: 127.0.0.1
  

  
install: true
script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.4.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.0.4/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - ${PWD}/mongodb-linux-x86_64-3.0.4/bin/mongorestore dump/
  - "cd WebRTC/"
  - 'npm install'
  - 'npm update'
  - "npm install forever -g"
  - "npm start"
  - 'chmod 0777 ./node_modules/.bin/mocha'
  - "npm test"
env:
  - XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
  

sudo: required