language: node_js
node_js:
  - "5"
before_install:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
  
script:
  - "ls"
  - "mongo coderdojo initialize.js"
  - "cd WebRTC/"
  - "java -jar ./test/selenium-server-standalone-2.52.0.jar &"
  - sleep 5
  - "npm install"
  - "npm update"
  - "npm install forever -g"
  - "forever start bin/www.js"
  - "npm test"
env:
  - XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
services:
  - mongodb
sudo: requireds

