language: node_js
node_js:
  - "4"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "mongo coderdojo initialize.js"
  - "cd /WebRTC"
  
before_install:
  - "java -jar ./test/selenium-server-standalone-2.52.0.jar &"
  - sleep 5
install:
  - "npm install"
  - "npm update"
  - "npm install forever -g"
  - "forever bin/www.js"
env:
  - XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
services:
  - mongodb
sudo: requireds
