language: node_js

node_js:
  - "4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  sauce_connect: 
    username: "CoderDojoDev"
    access_key: "d079bf09-33be-4565-aea4-f07ffd191a7d"
    direct_domains: *.saucelabs.com
 
  
install: true
script:
  - "mongo coderdojo initialize.js"
  - "cd WebRTC/"
  - sleep 3
  - 'npm install'
  - 'npm update'
  - "npm install forever -g"
  - "npm start"
  - 'chmod 0777 ./node_modules/.bin/mocha'
  - "npm test"
env:
  - CXX=g++-4.8 XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
  
services:
  - mongodb
sudo: required

