language: node_js

node_js:
  - "4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "nohup bash -c 'java -jar WebRTC/test/selenium-server-standalone-2.52.0.jar &'"
  - sleep 3 # give xvfb some time to start
script:
  - "ls"
  - "mongo coderdojo initialize.js"
  - "cd WebRTC/"
  - sleep 1
  - "npm install forever -g"
  - 'sudo chmod 777 ../runComServer.sh'
  - 'chmod 0777 ./node_modules/.bin/mocha'
  - "../runComServer.sh"
  - "npm test"
env:
  - CXX=g++-4.8 XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
  
services:
  - mongodb
sudo: requireds

