language: node_js

node_js:
  - "0.12"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  
install: true
script:
  - "mongo coderdojo initialize.js"
  - "cd WebRTC/"
  - "java -jar ./test/selenium-server-standalone-2.50.jar -firefoxProfileTemplate ./test/browser_certificate"
  - sleep 5
  - 'npm install'
  - 'npm update'
  - "npm install forever -g"
  - "npm start"
  - 'chmod 0777 ./node_modules/.bin/mocha'
  - "./node_modules/.bin/mocha ./test/MentorHandlerTest.js"
env:
  - XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
  
services:
  - mongodb
sudo: required

