language: node_js

node_js:
  - "4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "java -jar WebRTC/test/selenium-server-standalone-2.52.0.jar &"
  
install: true
script:
  - "mongo coderdojo initialize.js"
  - "cd WebRTC/"
  - sleep 1
  - 'npm install'
  - 'npm update'
  - "npm install forever -g"
  - "npm start"
  - 'chmod 0777 ./node_modules/.bin/mocha'
  - "npm test"
env:
  - CXX=g++-4.8 XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
  
services:
  - mongodb
sudo: false

