language: node_js

node_js:
  - "0.12"

addons:
  sauce_connect: 
    username: "CoderDojoDev"
    access_key: "d079bf09-33be-4565-aea4-f07ffd191a7d"
    direct-domains: 127.0.0.1
  
install: true
script:
  - "mongo coderdojo initialize.js"
  - "cd WebRTC/"
  - sleep 5
  - 'npm install'
  - 'npm update'
  - "npm install forever -g"
  - "npm start"
  - 'chmod 0777 ./node_modules/.bin/mocha'
  - "./node_modules/.bin/mocha ./test/MentorHandlerTest.js"
env:
  - XIRSYS=d61e9bc4-ef33-11e5-99b3-f77709746db4
  
services:
  - mongodb
sudo: required

